# Base da Linguagem
FROM node:postgres:13
# Definição do Diretório-Pasta do Projeto
WORKDIR /atvDocker
# Instalação de dependências
COPY package.json ./
# Cópia de Código Fonte - com container criado
COPY . .
# Compilar o projeto
RUN npm run build
# Identificar a porta 
EXPOSE 8080
#Comandos de Inicialização
CMD ["npm", "start"]