# Base da Linguagem
FROM node:14-alpine

# Definição do Diretório-Pasta do Projeto
WORKDIR /atvdocker

# Instalação de dependências
COPY ./front/package.json ./front/package-lock.json ./
RUN npm install --force

# Verifique as dependências instaladas
RUN npm list --depth=0

# Compilar o projeto
RUN npm run build

# Identificar a porta 
EXPOSE 3000

# Cópia de Código Fonte - com container criado
COPY . .

# Comandos de Inicialização
CMD ["npm", "start"]
