# Base da Linguagem
FROM node:14-alpine

# Definição do Diretório-Pasta do Projeto
WORKDIR /atvdocker

# Instalação de dependências
COPY package*.json package-lock ./ 
RUN npm install  

# Cópia de Código Fonte - com container criado
COPY . .

# Compilar o projeto
RUN npm run build

# Identificar a porta 
EXPOSE 3000

# Comandos de Inicialização
CMD ["npm", "start"]
